site_name: DSS Core Spec
theme:
  name: "material"
markdown_extensions:
  - admonition
nav:
  - Home: index.html
  - Assets:
      - Overview: assets/assets.md
      - Audio: assets/audio.md
      - Characters: assets/characters.md
      - Sets: assets/sets.md
  - Storyline:
      - Overview: storyline/storyline.md
      - Cameras: storyline/cameras.md
      - Characters: storyline/characters.md
      - Scenes: storyline/scenes.md
